name: Deploy AWS Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'lambda/**'

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761765191:role/GitHub
          aws-region: us-east-1

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../function.zip .
          cd ..

      - name: Deploy to AWS
        run: |
          
          FUNCTION_NAME="mi-primera-lambda" 
          
         
          ROLE_ARN="arn:aws:iam::288761765191:role/GitHub"

          if aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1; then
            echo "Actualizando código de la función existente..."
            aws lambda update-function-code \
              --function-name $FUNCTION_NAME \
              --zip-file fileb://function.zip
          else
            echo "Creando función nueva en AWS..."
            aws lambda create-function \
              --function-name $FUNCTION_NAME \
              --runtime python3.12 \
              --role $ROLE_ARN \
              --handler lambda_function.lambda_handler \
              --zip-file fileb://function.zip
          fi
