name: Deploy AWS Lambdas

on:
  push:
    branches: [ main ]
    paths:
      - 'lambda/**'

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # Usamos el secreto para el ARN del rol
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Deploy Changed Lambdas
        env:
          # Pasamos el secreto como variable de entorno para el script de abajo
          ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
        run: |
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep '^lambda/' | cut -d/ -f2 | uniq)

          for DIR in $CHANGED_DIRS; do
            if [ -d "lambda/$DIR" ]; then
              echo "--- Procesando: $DIR ---"
              
              FUNCTION_NAME="$DIR"

              cd lambda/$DIR
              if [ -f "requirements.txt" ]; then
                pip install -r requirements.txt -t .
              fi

              zip -r ../../$DIR.zip .
              cd ../..

              if aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1; then
                aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file fileb://$DIR.zip
              else
                # Usamos la variable de entorno $ROLE_ARN definida arriba
                aws lambda create-function \
                  --function-name $FUNCTION_NAME \
                  --runtime python3.12 \
                  --role $ROLE_ARN \
                  --handler lambda_function.lambda_handler \
                  --zip-file fileb://$DIR.zip
              fi

              rm $DIR.zip
            fi
          done
