name: Deploy AWS Lambdas

on:
  push:
    branches: [ main ]
    paths:
      - 'lambda/**'

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::288761765191:role/GitHub
          aws-region: us-east-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Deploy Changed Lambdas
        run: |
          # 1. Identificar carpetas modificadas
          CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep '^lambda/' | cut -d/ -f2 | uniq)

          for DIR in $CHANGED_DIRS; do
            if [ -d "lambda/$DIR" ]; then
              echo "--- Procesando: $DIR ---"
              
              FUNCTION_NAME="$DIR"
              ROLE_ARN="arn:aws:iam::288761765191:role/GitHub"

              cd lambda/$DIR

              # 2. Instalar dependencias si existe requirements.txt
              if [ -f "requirements.txt" ]; then
                echo "Instalando dependencias en la carpeta local..."
                pip install -r requirements.txt -t .
              fi

              # 3. Crear el paquete ZIP
              zip -r ../../$DIR.zip .
              cd ../..

              # 4. Desplegar en AWS
              if aws lambda get-function --function-name $FUNCTION_NAME > /dev/null 2>&1; then
                echo "Actualizando $FUNCTION_NAME..."
                aws lambda update-function-code \
                  --function-name $FUNCTION_NAME \
                  --zip-file fileb://$DIR.zip
              else
                echo "Creando $FUNCTION_NAME..."
                aws lambda create-function \
                  --function-name $FUNCTION_NAME \
                  --runtime python3.12 \
                  --role $ROLE_ARN \
                  --handler lambda_function.lambda_handler \
                  --zip-file fileb://$DIR.zip
              fi

              # Limpieza
              rm $DIR.zip
            fi
          done
